server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/nie?createDatabaseIfNotExist=true
#    username: root
#    password: Shan1104
    url: jdbc:mysql://172.17.0.1:3306/nie?createDatabaseIfNotExist=true
    password: GT56&8jhr$c#
    username: NIERemote
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace